{
 "title": "Application metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "appinsights",
    "query": {}
   },
   {
    "name": "servicebus",
    "query": {}
   },
   {
    "name": "creditdb",
    "query": {}
   },
   {
    "name": "bookingdb",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Credit Api",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "credit-api",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Processor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "booking-processor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Credit api metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "credits.created",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(sum_over_time(credits_created[$__range]))",
     "legendFormat": "Credits created",
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "credits.transaction.value.added",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(sum_over_time(credits_transaction_value_added_sek[$__range]))",
     "legendFormat": "Transactions in SEK",
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Events processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "events.start.booking.consumed",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(sum_over_time(events_start_booking_consumed[$__range]))",
     "legendFormat": "Start Booking",
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "events.transaction.booking.consumed",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(sum_over_time(events_start_booking_consumed[$__range]))",
     "legendFormat": "Start Booking",
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "credit api",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "swedencentral",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "swedencentral",
        "resourceGroup": "$rg",
        "resourceName": "$appinsights",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": " availabilityResults\r\n| extend percentage = toint(success) * 100\r\n| summarize avg(percentage) by bin(timestamp, 5m)",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Insights/components/$appinsights"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Credit Api",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "credit-api" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Events processed over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "events.start.booking.consumed",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(events_start_booking_consumed)",
     "legendFormat": "Start Booking",
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "events.transaction.booking.consumed",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "Microsoft.Insights/components", "resourceGroup": "$rg", "resourceName": "$appinsights", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "expr": "sum(events_start_booking_consumed)",
     "legendFormat": "Start Booking",
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cpu usages by credit api replica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "(($B / 10000000000) / 0.5) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Service bus messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.servicebus/namespaces",
        "region": "",
        "resourceGroup": "$rg",
        "resourceName": "$servicebus",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.servicebus/namespaces",
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.servicebus/namespaces",
        "region": "",
        "resourceGroup": "$rg",
        "resourceName": "$servicebus",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cpu usages by booking processor replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "(($B / 10000000000) / 0.5) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Booking processor replicas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resourceGroup": "$rg",
      "resourceName": "Booking-processor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability test duration per location",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "availabilityResults\r\n| where notempty(duration)\r\n| extend availabilityResult_duration = iif(itemType == 'availabilityResult', duration, todouble(''))\r\n| summarize durationPerLocation=sum(availabilityResult_duration) / sum(itemCount) by bin(timestamp, 5m), location\r\n| evaluate pivot(location, sum(durationPerLocation))\r\n| order by timestamp desc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Insights/components/$appinsights"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Database space used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ resourcename }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$creditdb",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{ resourcename }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$bookingdb",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}